// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for PaymentStatus.
const (
	Canceled  PaymentStatus = "canceled"
	Failed    PaymentStatus = "failed"
	Pending   PaymentStatus = "pending"
	Refunded  PaymentStatus = "refunded"
	Succeeded PaymentStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the PaymentStatus enum.
func (e PaymentStatus) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Refunded:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Defines values for ReceiptPaymentMethod.
const (
	Advance        ReceiptPaymentMethod = "advance"
	Credit         ReceiptPaymentMethod = "credit"
	CreditPayment  ReceiptPaymentMethod = "credit_payment"
	FullPayment    ReceiptPaymentMethod = "full_payment"
	FullPrepayment ReceiptPaymentMethod = "full_prepayment"
	PartialPayment ReceiptPaymentMethod = "partial_payment"
	Prepayment     ReceiptPaymentMethod = "prepayment"
)

// Valid indicates whether the value is a known member of the ReceiptPaymentMethod enum.
func (e ReceiptPaymentMethod) Valid() bool {
	switch e {
	case Advance:
		return true
	case Credit:
		return true
	case CreditPayment:
		return true
	case FullPayment:
		return true
	case FullPrepayment:
		return true
	case PartialPayment:
		return true
	case Prepayment:
		return true
	default:
		return false
	}
}

// Defines values for ReceiptPaymentObject.
const (
	AgentCommission      ReceiptPaymentObject = "agent_commission"
	Another              ReceiptPaymentObject = "another"
	Commodity            ReceiptPaymentObject = "commodity"
	Composite            ReceiptPaymentObject = "composite"
	Excise               ReceiptPaymentObject = "excise"
	GamblingBet          ReceiptPaymentObject = "gambling_bet"
	GamblingPrize        ReceiptPaymentObject = "gambling_prize"
	IntellectualActivity ReceiptPaymentObject = "intellectual_activity"
	Job                  ReceiptPaymentObject = "job"
	Lottery              ReceiptPaymentObject = "lottery"
	LotteryPrize         ReceiptPaymentObject = "lottery_prize"
	Payment              ReceiptPaymentObject = "payment"
	Service              ReceiptPaymentObject = "service"
)

// Valid indicates whether the value is a known member of the ReceiptPaymentObject enum.
func (e ReceiptPaymentObject) Valid() bool {
	switch e {
	case AgentCommission:
		return true
	case Another:
		return true
	case Commodity:
		return true
	case Composite:
		return true
	case Excise:
		return true
	case GamblingBet:
		return true
	case GamblingPrize:
		return true
	case IntellectualActivity:
		return true
	case Job:
		return true
	case Lottery:
		return true
	case LotteryPrize:
		return true
	case Payment:
		return true
	case Service:
		return true
	default:
		return false
	}
}

// Defines values for ReceiptTax.
const (
	None   ReceiptTax = "none"
	Vat0   ReceiptTax = "vat0"
	Vat10  ReceiptTax = "vat10"
	Vat105 ReceiptTax = "vat105"
	Vat107 ReceiptTax = "vat107"
	Vat110 ReceiptTax = "vat110"
	Vat122 ReceiptTax = "vat122"
	Vat22  ReceiptTax = "vat22"
	Vat5   ReceiptTax = "vat5"
	Vat7   ReceiptTax = "vat7"
)

// Valid indicates whether the value is a known member of the ReceiptTax enum.
func (e ReceiptTax) Valid() bool {
	switch e {
	case None:
		return true
	case Vat0:
		return true
	case Vat10:
		return true
	case Vat105:
		return true
	case Vat107:
		return true
	case Vat110:
		return true
	case Vat122:
		return true
	case Vat22:
		return true
	case Vat5:
		return true
	case Vat7:
		return true
	default:
		return false
	}
}

// Defines values for ReceiptTaxation.
const (
	Esn              ReceiptTaxation = "esn"
	Osn              ReceiptTaxation = "osn"
	Patent           ReceiptTaxation = "patent"
	UsnIncome        ReceiptTaxation = "usn_income"
	UsnIncomeOutcome ReceiptTaxation = "usn_income_outcome"
)

// Valid indicates whether the value is a known member of the ReceiptTaxation enum.
func (e ReceiptTaxation) Valid() bool {
	switch e {
	case Esn:
		return true
	case Osn:
		return true
	case Patent:
		return true
	case UsnIncome:
		return true
	case UsnIncomeOutcome:
		return true
	default:
		return false
	}
}

// CreatePaymentRequest defines model for CreatePaymentRequest.
type CreatePaymentRequest struct {
	AmountMinor   int64     `json:"amount_minor"`
	Currency      string    `json:"currency"`
	Customer      *Customer `json:"customer,omitempty"`
	Description   *string   `json:"description,omitempty"`
	OrderId       string    `json:"order_id"`
	PaymentMethod *string   `json:"payment_method,omitempty"`
	Receipt       Receipt   `json:"receipt"`
}

// Customer defines model for Customer.
type Customer struct {
	Email *openapi_types.Email `json:"email,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// PaymentResponse defines model for PaymentResponse.
type PaymentResponse struct {
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	OrderId     string             `json:"order_id"`
	PaymentId   openapi_types.UUID `json:"payment_id"`
	PaymentUrl  *string            `json:"payment_url,omitempty"`
	Status      PaymentStatus      `json:"status"`
}

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus string

// Receipt defines model for Receipt.
type Receipt struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Items    []ReceiptItem        `json:"items"`
	Phone    *string              `json:"phone,omitempty"`
	Taxation ReceiptTaxation      `json:"taxation"`
}

// ReceiptItem defines model for ReceiptItem.
type ReceiptItem struct {
	AmountMinor   int64                 `json:"amount_minor"`
	Name          string                `json:"name"`
	PaymentMethod *ReceiptPaymentMethod `json:"payment_method,omitempty"`
	PaymentObject *ReceiptPaymentObject `json:"payment_object,omitempty"`
	PriceMinor    int64                 `json:"price_minor"`
	Quantity      float64               `json:"quantity"`
	Tax           ReceiptTax            `json:"tax"`
}

// ReceiptPaymentMethod defines model for ReceiptPaymentMethod.
type ReceiptPaymentMethod string

// ReceiptPaymentObject defines model for ReceiptPaymentObject.
type ReceiptPaymentObject string

// ReceiptTax defines model for ReceiptTax.
type ReceiptTax string

// ReceiptTaxation defines model for ReceiptTaxation.
type ReceiptTaxation string

// WebhookResponse defines model for WebhookResponse.
type WebhookResponse struct {
	Status string `json:"status"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// XAPIKey defines model for XAPIKey.
type XAPIKey = string

// XSignature defines model for XSignature.
type XSignature = string

// XTimestamp defines model for XTimestamp.
type XTimestamp = string

// Error defines model for Error.
type Error = ErrorResponse

// CreatePaymentParams defines parameters for CreatePayment.
type CreatePaymentParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
	XAPIKey        XAPIKey         `json:"X-API-Key"`
	XTimestamp     XTimestamp      `json:"X-Timestamp"`
	XSignature     XSignature      `json:"X-Signature"`
}

// ProviderWebhookJSONBody defines parameters for ProviderWebhook.
type ProviderWebhookJSONBody map[string]interface{}

// ProviderWebhookFormdataBody defines parameters for ProviderWebhook.
type ProviderWebhookFormdataBody struct {
}

// CreatePaymentJSONRequestBody defines body for CreatePayment for application/json ContentType.
type CreatePaymentJSONRequestBody = CreatePaymentRequest

// ProviderWebhookJSONRequestBody defines body for ProviderWebhook for application/json ContentType.
type ProviderWebhookJSONRequestBody ProviderWebhookJSONBody

// ProviderWebhookFormdataRequestBody defines body for ProviderWebhook for application/x-www-form-urlencoded ContentType.
type ProviderWebhookFormdataRequestBody ProviderWebhookFormdataBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Create payment
	// (POST /payments)
	CreatePayment(w http.ResponseWriter, r *http.Request, params CreatePaymentParams)
	// Get payment
	// (GET /payments/{payment_id})
	GetPayment(w http.ResponseWriter, r *http.Request, paymentId openapi_types.UUID)
	// Provider webhook
	// (POST /provider-webhooks/{provider_name})
	ProviderWebhook(w http.ResponseWriter, r *http.Request, providerName string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create payment
// (POST /payments)
func (_ Unimplemented) CreatePayment(w http.ResponseWriter, r *http.Request, params CreatePaymentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get payment
// (GET /payments/{payment_id})
func (_ Unimplemented) GetPayment(w http.ResponseWriter, r *http.Request, paymentId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Provider webhook
// (POST /provider-webhooks/{provider_name})
func (_ Unimplemented) ProviderWebhook(w http.ResponseWriter, r *http.Request, providerName string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePayment operation middleware
func (siw *ServerInterfaceWrapper) CreatePayment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreatePaymentParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	// ------------- Required header parameter "X-API-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-Key")]; found {
		var XAPIKey XAPIKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-API-Key", valueList[0], &XAPIKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-Key", Err: err})
			return
		}

		params.XAPIKey = XAPIKey

	} else {
		err := fmt.Errorf("Header parameter X-API-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-Key", Err: err})
		return
	}

	// ------------- Required header parameter "X-Timestamp" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Timestamp")]; found {
		var XTimestamp XTimestamp
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Timestamp", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Timestamp", valueList[0], &XTimestamp, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Timestamp", Err: err})
			return
		}

		params.XTimestamp = XTimestamp

	} else {
		err := fmt.Errorf("Header parameter X-Timestamp is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Timestamp", Err: err})
		return
	}

	// ------------- Required header parameter "X-Signature" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Signature")]; found {
		var XSignature XSignature
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Signature", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Signature", valueList[0], &XSignature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Signature", Err: err})
			return
		}

		params.XSignature = XSignature

	} else {
		err := fmt.Errorf("Header parameter X-Signature is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Signature", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePayment(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPayment operation middleware
func (siw *ServerInterfaceWrapper) GetPayment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "payment_id" -------------
	var paymentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "payment_id", chi.URLParam(r, "payment_id"), &paymentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "payment_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPayment(w, r, paymentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProviderWebhook operation middleware
func (siw *ServerInterfaceWrapper) ProviderWebhook(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider_name" -------------
	var providerName string

	err = runtime.BindStyledParameterWithOptions("simple", "provider_name", chi.URLParam(r, "provider_name"), &providerName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProviderWebhook(w, r, providerName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/payments", wrapper.CreatePayment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/payments/{payment_id}", wrapper.GetPayment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/provider-webhooks/{provider_name}", wrapper.ProviderWebhook)
	})

	return r
}

type ErrorJSONResponse ErrorResponse

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePaymentRequestObject struct {
	Params CreatePaymentParams
	Body   *CreatePaymentJSONRequestBody
}

type CreatePaymentResponseObject interface {
	VisitCreatePaymentResponse(w http.ResponseWriter) error
}

type CreatePayment200JSONResponse PaymentResponse

func (response CreatePayment200JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayment201JSONResponse PaymentResponse

func (response CreatePayment201JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayment400JSONResponse struct{ ErrorJSONResponse }

func (response CreatePayment400JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayment401JSONResponse ErrorResponse

func (response CreatePayment401JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPaymentRequestObject struct {
	PaymentId openapi_types.UUID `json:"payment_id"`
}

type GetPaymentResponseObject interface {
	VisitGetPaymentResponse(w http.ResponseWriter) error
}

type GetPayment200JSONResponse PaymentResponse

func (response GetPayment200JSONResponse) VisitGetPaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPayment404JSONResponse struct{ ErrorJSONResponse }

func (response GetPayment404JSONResponse) VisitGetPaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ProviderWebhookRequestObject struct {
	ProviderName string `json:"provider_name"`
	JSONBody     *ProviderWebhookJSONRequestBody
	FormdataBody *ProviderWebhookFormdataRequestBody
}

type ProviderWebhookResponseObject interface {
	VisitProviderWebhookResponse(w http.ResponseWriter) error
}

type ProviderWebhook200JSONResponse WebhookResponse

func (response ProviderWebhook200JSONResponse) VisitProviderWebhookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ProviderWebhook400JSONResponse struct{ ErrorJSONResponse }

func (response ProviderWebhook400JSONResponse) VisitProviderWebhookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Create payment
	// (POST /payments)
	CreatePayment(ctx context.Context, request CreatePaymentRequestObject) (CreatePaymentResponseObject, error)
	// Get payment
	// (GET /payments/{payment_id})
	GetPayment(ctx context.Context, request GetPaymentRequestObject) (GetPaymentResponseObject, error)
	// Provider webhook
	// (POST /provider-webhooks/{provider_name})
	ProviderWebhook(ctx context.Context, request ProviderWebhookRequestObject) (ProviderWebhookResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePayment operation middleware
func (sh *strictHandler) CreatePayment(w http.ResponseWriter, r *http.Request, params CreatePaymentParams) {
	var request CreatePaymentRequestObject

	request.Params = params

	var body CreatePaymentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePayment(ctx, request.(CreatePaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePayment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePaymentResponseObject); ok {
		if err := validResponse.VisitCreatePaymentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPayment operation middleware
func (sh *strictHandler) GetPayment(w http.ResponseWriter, r *http.Request, paymentId openapi_types.UUID) {
	var request GetPaymentRequestObject

	request.PaymentId = paymentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPayment(ctx, request.(GetPaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPayment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPaymentResponseObject); ok {
		if err := validResponse.VisitGetPaymentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProviderWebhook operation middleware
func (sh *strictHandler) ProviderWebhook(w http.ResponseWriter, r *http.Request, providerName string) {
	var request ProviderWebhookRequestObject

	request.ProviderName = providerName
	if strings.HasPrefix(r.Header.Get("Content-Type"), "application/json") {

		var body ProviderWebhookJSONRequestBody
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
		request.JSONBody = &body

	}
	if strings.HasPrefix(r.Header.Get("Content-Type"), "application/x-www-form-urlencoded") {
		if err := r.ParseForm(); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode formdata: %w", err))
			return
		}
		var body ProviderWebhookFormdataRequestBody
		if err := runtime.BindForm(&body, r.Form, nil, nil); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't bind formdata: %w", err))
			return
		}
		request.FormdataBody = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ProviderWebhook(ctx, request.(ProviderWebhookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProviderWebhook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ProviderWebhookResponseObject); ok {
		if err := validResponse.VisitProviderWebhookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
